# Generated by Django 5.0.6 on 2025-09-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.CharField(max_length=1024)),
                ("columns_json", models.JSONField(default=list)),
                ("n_rows", models.IntegerField(default=0)),
                ("freq_guess", models.CharField(blank=True, default="", max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="RagDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.CharField(max_length=1024)),
                ("pages", models.IntegerField(default=0)),
                ("size_mb", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("params", models.JSONField(default=dict)),
                ("status", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="evidra.dataset"
                    ),
                ),
                (
                    "rag_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evidra.ragdoc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=128)),
                ("target", models.CharField(max_length=128)),
                ("effect", models.FloatField(default=0.0)),
                ("prob", models.FloatField(default=0.0)),
                ("sign", models.CharField(default="+", max_length=1)),
                ("eval_has", models.BooleanField(null=True)),
                ("eval_dir", models.BooleanField(null=True)),
                ("eval_sign", models.BooleanField(null=True)),
                ("type_code", models.IntegerField(null=True)),
                ("citations", models.JSONField(default=list)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="evidra.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(max_length=16)),
                ("text", models.TextField()),
                ("soft_deleted", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="evidra.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mermaid_step1", models.TextField(blank=True, default="")),
                ("mermaid_step3", models.TextField(blank=True, default="")),
                ("markdown_table", models.TextField(blank=True, default="")),
                (
                    "plotly_html_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="evidra.run",
                    ),
                ),
            ],
        ),
    ]
