# Generated by Django 5.2.6 on 2025-09-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifact",
                to="evidra.run",
            ),
        ),
    ]
