# Generated by Django 5.2.6 on 2025-09-23 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidra", "0002_alter_edge_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="lag",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="edge",
            name="effect",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="edge",
            name="prob",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="edge",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="evidra.run",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="sign",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="edge",
            name="source",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="edge",
            name="target",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(fields=["run"], name="evidra_edge_run_id_f73da4_idx"),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["run", "source", "target"], name="evidra_edge_run_id_50616e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("run", "source", "target", "lag"),
                name="uniq_edge_per_run_src_tgt_lag",
            ),
        ),
    ]
